general:
  cfApiEndpoint: 'https://api.cf.us10.hana.ondemand.com'
  cfOrg: 'cc48e02etrial'
  cfSpace: 'dev'
  cfCredentialsId: 'c389497-52d5-45b5-a4ed-b541daac12f'
  cfServiceInstance: 'abapEnvironmentPipeline'
  cfServiceKeyName: 'jenkins_sap_com_0510'
stages:
  Prepare System:
    cfServiceManifest: 'manifest.yml'
    cfServiceKeyConfig: 'sap_com_0510.json'
  Clone Repositories:
    repositoryNames: ['/DMO/REPO']
  ATC:
    atcConfig: 'atcConfig.yml'
steps:
  cloudFoundryDeleteService:
    cfDeleteServiceKeys: true

